repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
      - id: check-ast
      - id: requirements-txt-fixer

  - repo: local
    hooks:
      - id: yapf
        name: Running yapf
        language: system
        entry: hatch --config config.toml run yapf -i
        types: [python]
      - id: isort
        name: Running isort
        stages: [commit]
        language: system
        entry: hatch --config config.toml run isort
        types: [python]
      - id: mypy
        name: Running mypy
        stages: [commit]
        language: system
        entry: hatch --config config.toml run telegram:mypy
        args: [--install-types, --non-interactive]
        types: [python]
